return {
	{
		"williamboman/mason.nvim",
		keys = {},
		opts = {
			ensure_installed = {
				"stylua",
				"shellcheck",
				"eslint_d",
				"eslint-lsp",
				"gopls",
				"html-lsp",
				"json-lsp",
				"prettier",
				"graphql-language-service-cli",
				"cspell",
				"angular-language-server",
				"bash-language-server",
				"pyright",
				"yapf",
				"black",
				"typos",
				"write-good",
				"css-lsp",
				"gomodifytags",
				"impl",
				"delve",
				"goimports",
				"gofumpt",
				"omnisharp",
				"dart-debug-adapter",
			},
		},
	},
}
